import "@styles/global.css";

import {IBM_Plex_Mono, Rubik_Mono_One} from "next/font/google";

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-ibmPlexMono",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const rubikMonoOne = Rubik_Mono_One({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubikMonoOne",
  weight: "400",
});

export const metadata = {
  title: "Echology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${ibmPlexMono.className} ${rubikMonoOne.variable} tracking-[1px]`}
    >
      <body>
          <main className="app">{children}</main>
      </body>
    </html>
  );
}
